#!/usr/bin/perl -w
use strict;
use Net::Telnet;

sub read_cfg {
	my ($file) = @_;
	open(my $f, $file) or die "$file: $!";
	my $str = <$f>;
	chomp $str;
	close $f;
	return split /\s+/, $str;
}


my ($cfg, @cmd) = @ARGV;

if (not defined $cfg or not -f $cfg) {
	print "Usage: $0 config_file commands\n";
	exit;
}

my ($host, $login, $password, $type) = read_cfg($cfg);
$type ||= 'juniper';

my $c = Net::Telnet->new( Host => $host, Timeout => 5 );

print $type, "\n";
if ($type eq 'juniper') {
	$c->login($login, $password);
	$c->cmd('set cli screen-length 0');
}
elsif ($type eq 'huawei') {
	$c->prompt('/<.+>$/');
	$c->login($login, $password);
}

print $c->cmd(join " ", @cmd);
